### ISSUE TITLE
Adding the actual code to the repo

### ISSUE THREAD

**Issue by JamesBrightman** [ryry6/f1-radar-releases#1]
Would it be possible to add the actual code of the executable program to this repo? A lot of people aren't 100% happy to download and run unknown .exe files. Thanks.

**Comment by ryry6** [comment]
Yeah I understand and the source code is coming but even if the source code was here I would still encourage people to scan whatever they download and be skeptical. It uses the [Squirrel Windows](https://github.com/Squirrel/Squirrel.Windows) installer/updater and it's whole point is to have a single exe to do all the work. I've done what I can by buying a certificate and digitally signing the exe. If you have any other ideas to make people more at ease with it I'll be happy to hear them.

Thanks

**Comment by JamesBrightman** [comment]
Appreciate the response, looking forward to seeing the code at some point, I'd be interested in taking on a similar project to this!

**Comment by ryanabaker** [comment]
Any update on adding the source code to the repo? I am trying to create something similar, however I am stuck on what to do with the m_worldForwardDirX, m_worldForwardDirZ, m_worldRightDirX, m_worldRightDirY values to display them to a 2D canvas.

Any help much appreciated.

**Comment by ryanabaker** [comment]
See #3 for update.

**Comment by JamesBrightman** [comment]
> See #3 for update.

That's disappointing, another few years go by and I'd still like to make something like this!
